package vista;

import controlador.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by poo2 on 25/05/2016.
 */
public class Menu extends JFrame implements ActionListener {
  private JPanel menu;
  private JButton altaDeLíneasButton;
  private JButton altaDeAutobusesButton;
  private JButton salirButton;
  private Controlador ctrl;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    menu = new JPanel();
    menu.setLayout(new GridBagLayout());
    altaDeAutobusesButton = new JButton();
    altaDeAutobusesButton.setText("Alta de autobuses");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menu.add(altaDeAutobusesButton, gbc);
    altaDeLíneasButton = new JButton();
    altaDeLíneasButton.setText("Alta de líneas");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menu.add(altaDeLíneasButton, gbc);
    salirButton = new JButton();
    salirButton.setText("Salir");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    menu.add(salirButton, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    gbc.ipady = 100;
    menu.add(spacer1, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return menu;
  }

  private class AccionLineaNueva implements ActionListener {

    @Override
    public void actionPerformed(ActionEvent e) {
      new Linea("Linea nueva", ctrl);
    }
  }

  public static void main(String[] args) {
    Menu m = new Menu("Menu");
  }

  public Menu(String titulo) {
    super(titulo);

    setContentPane(menu);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setLocationRelativeTo(null);
    setVisible(true);
    ctrl = new Controlador();

    salirButton.addActionListener(this);
    altaDeLíneasButton.addActionListener(new AccionLineaNueva());
  }

  @Override
  public void actionPerformed(ActionEvent e) {
    dispose();
  }

}
